### ISSUE TITLE
hazelcast-exporter:0.8.0 doesn't work with zeebe:0.23.1 out of the box

### ISSUE THREAD

**Issue by nervgh** [zeebe-io/zeebe-hazelcast-exporter#48]
Hi everyone!

First of all, thank you for your efforts :rocket: 

I'm configuring the exporter to work with broker via environment variables and I have some troubles.

### Steps to reproduce

1. I have the Dockerfile

    ```dockerfile
    # The image from Docker Hub
    FROM camunda/zeebe:0.23.1

    ARG ZEEBE_HAZELCAST_EXPORTER_URI=https://github.com/zeebe-io/zeebe-hazelcast-exporter/releases/download/0.8.0/zeebe-hazelcast-exporter-0.8.0-jar-with-dependencies.jar
    ARG ZEEBE_HAZELCAST_EXPORTER_OUTPUT=/usr/local/zeebe/lib/zeebe-hazelcast-exporter.jar

    RUN wget -qO $ZEEBE_HAZELCAST_EXPORTER_OUTPUT $ZEEBE_HAZELCAST_EXPORTER_URI

    # Exporters
    # https://github.com/zeebe-io/zeebe-hazelcast-exporter/tree/0.8.0#manual
    ENV ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH=$ZEEBE_HAZELCAST_EXPORTER_OUTPUT
    ENV ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME="io.zeebe.hazelcast.exporter.HazelcastExporter"
    ENV ZEEBE_BROKER_EXPORTERS_HAZELCAST_ARGS_PORT=5701
    ```

2. I build it via docker CLI next way:

    ```sh
    docker build . 
    ```

   It results me some `<image_id>`.

3. Then I run Zeebe with Hazelcast like this:

    ```sh
    docker run -it <image_id_from_previous_step>
    ```

4. After that I see some logs

    ```json
    ...
    "exporters" : {
      "hazelcast" : {
        "jarPath" : "/usr/local/zeebe/lib/zeebe-hazelcast-exporter.jar",
        "className" : "io.zeebe.hazelcast.exporter.HazelcastExporter",
        "args" : {
          "port" : "5701"
        },
        "external" : true
      }
    },
    ...
    ```

5. and the error

    ```
    Apr 28, 2020 12:36:50 PM com.hazelcast.instance.HazelcastInstanceFactory
    WARNING: Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
     --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
    2020-04-28 12:36:50.896 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] INFO  com.hazelcast.instance.AddressPicker - [LOCAL] [dev] [3.12.6] Prefer IPv4 stack is true, prefer IPv6 addresses is false
    2020-04-28 12:36:50.900 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] INFO  com.hazelcast.instance.AddressPicker - [LOCAL] [dev] [3.12.6] Picked [172.17.0.2]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
    2020-04-28 12:36:50.905 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] ERROR io.zeebe.util.actor - Uncaught exception in 'Broker-0-Exporter-1' in phase 'STARTED'. Continuing with next job.
    com.hazelcast.core.HazelcastException: ServiceLoader didn't find any services registered under com.hazelcast.instance.NodeExtension
	    at com.hazelcast.instance.NodeExtensionFactory.create(NodeExtensionFactory.java:86) ~[zeebe-hazelcast-exporter.jar:0.8.0]
	    at com.hazelcast.instance.DefaultNodeContext.createNodeExtension(DefaultNodeContext.java:59) ~[zeebe-hazelcast-exporter.jar:0.8.0]
	    at com.hazelcast.instance.Node.<init>(Node.java:223) ~[zeebe-hazelcast-exporter.jar:0.8.0]
	    at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:161) ~[zeebe-hazelcast-exporter.jar:0.8.0]
	    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131) ~[zeebe-hazelcast-exporter.jar:0.8.0]
	    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:229) ~[zeebe-hazelcast-exporter.jar:0.8.0]
	    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:208) ~[zeebe-hazelcast-exporter.jar:0.8.0]
	    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:158) ~[zeebe-hazelcast-exporter.jar:0.8.0]
	    at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57) ~[zeebe-hazelcast-exporter.jar:0.8.0]
	    at io.zeebe.hazelcast.exporter.HazelcastExporter.open(HazelcastExporter.java:63) ~[zeebe-hazelcast-exporter.jar:0.8.0]
	    at io.zeebe.broker.exporter.stream.ExporterDirector.onSnapshotRecovered(ExporterDirector.java:225) ~[zeebe-broker-0.23.1.jar:0.23.1]
	    at io.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted(ExporterDirector.java:140) ~[zeebe-broker-0.23.1.jar:0.23.1]
	    at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.23.1.jar:0.23.1]
	    at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.1.jar:0.23.1]
	    at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.1.jar:0.23.1]
	    at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.1.jar:0.23.1]
	    at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.1.jar:0.23.1]
	    at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.1.jar:0.23.1]
    ```

Please, help me to find the way to solve the problem :smile:

**Comment by saig0** [comment]
Hi @nervgh,

thank you for reporting!

It seems that this issue is related to the exporter JAR path `/usr/local/zeebe/lib/zeebe-hazelcast-exporter.jar`. I'm not sure why. Maybe, a conflict with another JAR in this folder?

I recommend copying the JAR into a separate folder for exporters. For example,  `/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar`. (Similiar to the docker-compose file)

Does this work for you?

**Comment by nervgh** [comment]
@saig0 thank you one more time :v: 

That's it! 

I've changed my Dockerfile like bellow and it's work now :sparkles: 

```dockerfile
# The image from Docker Hub
FROM camunda/zeebe:0.23.1

ARG ZEEBE_HAZELCAST_EXPORTER_URI=https://github.com/zeebe-io/zeebe-hazelcast-exporter/releases/download/0.8.0/zeebe-hazelcast-exporter-0.8.0-jar-with-dependencies.jar
ARG ZEEBE_HAZELCAST_EXPORTER_DIR=/usr/local/zeebe/exporters
ARG ZEEBE_HAZELCAST_EXPORTER_FILENAME=$ZEEBE_HAZELCAST_EXPORTER_DIR/zeebe-hazelcast-exporter.jar

RUN mkdir -p $ZEEBE_HAZELCAST_EXPORTER_DIR \
  && wget -qO $ZEEBE_HAZELCAST_EXPORTER_FILENAME $ZEEBE_HAZELCAST_EXPORTER_URI

# https://github.com/zeebe-io/zeebe-hazelcast-exporter/tree/0.8.0#manual
ENV ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH=$ZEEBE_HAZELCAST_EXPORTER_FILENAME
ENV ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME="io.zeebe.hazelcast.exporter.HazelcastExporter"
ENV ZEEBE_BROKER_EXPORTERS_HAZELCAST_ARGS_PORT=5701
```
